services:

  printed.bundle.queue.command.ensure_vhost_exists_command:
    class: 'Printed\Bundle\Queue\Command\EnsureVhostExistsCommand'
    tags:
      - { name: 'console.command' }
    public: false

  printed.bundle.queue.command.maintenance_down_command:
    class: 'Printed\Bundle\Queue\Command\MaintenanceDownCommand'
    tags:
      - { name: 'console.command' }
    public: false

  printed.bundle.queue.command.maintenance_up_command:
    class: 'Printed\Bundle\Queue\Command\MaintenanceUpCommand'
    tags:
      - { name: 'console.command' }
    public: false

  printed.bundle.queue.command.maintenance_wait_for_running_command:
    class: 'Printed\Bundle\Queue\Command\MaintenanceWaitForRunningCommand'
    tags:
      - { name: 'console.command' }
    public: false

  printed.bundle.queue.command.requeue_task_command:
    class: 'Printed\Bundle\Queue\Command\RequeueTaskCommand'
    arguments:
      - '@monolog.logger'
    tags:
      - { name: 'console.command' }
    public: false

  printed.bundle.queue.command.store_new_deployment_stamp_command:
    class: 'Printed\Bundle\Queue\Command\StoreNewDeploymentStampCommand'
    arguments:
      - '@monolog.logger'
    tags:
      - { name: 'console.command' }
    public: false

